### PR TITLE
Readme: provide new version of devfiler

### PR DESCRIPTION
**Pull request by florianl**
Provide updated version of devfiler.

Fixes https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/163

### CODE REVIEW

**Review by athre0z — COMMENTED** [review]
Thank you (and whoever ended up creating the mac builds) for keeping devfiler alive! :) Since you didn't sign the macOS build, can you perhaps add the instructions on how to use xattr to make it run? Otherwise it'll be confusing for macOS users. Without running xattr, it says that the application is corrupted.

**Review by athre0z — APPROVED** [review]
👍

**Review by fabled — APPROVED** [review]
Thank you!

**Comment by tmm1** [comment]
fyi this build says devfiler-v0.7.0 when you extract it, but running the macos arm64 build it still identifies itself as 0.6.0 in the menu bar

**Comment by florianl** [comment]
thanks @tmm1 there was an issue with the release process. The displayed version number got fixed but no new release was produced.

**Pull request merged**
